### ISSUE TITLE
Do need update by date

### ISSUE THREAD

**Issue by quanghufi** [drunkleen/TimeFarm-Bot#1]
Hi, do i need update query date by date?

**Comment by drunkleen** [comment]
Short answer: No.

Long answer: The query string is valid for only 5 minutes, after which it expires. Therefore, you need to paste your query in the `query.conf` file. When running TimeFarm Bot, respond with "yes" to the `generate tokens from ./configs/query.conf` prompt. The bot will automatically generate a token from the given queries in the `query.conf` file, store it in the `tokens.conf` file, and then remove the query from `query.conf`.

After that, each time you run the program, it uses the tokens instead of the queries. If you have a new query from another account, simply paste it in the `query.conf` file, run the program, and confirm the prompt to generate a token. The bot will use the new query to generate and store a new token in `tokens.conf` alongside the existing token, enabling the bot to run both accounts.

**Comment by quanghufi** [comment]
hi bro, token available only 1 day, after that need collect new query
